sudo: false

language: java

jdk:
- oraclejdk8

services:
- docker
 
## Build and release to maven central
script:
- mvn clean verify --settings .travis/settings.xml -B -U

cache:
  directories:
    - $HOME/.m2

## export GPG details
before_deploy:
- echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
- echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

deploy:
  provider: script
  script: ./travis/release.sh
  skip_cleanup: true
  on:
    repo: johnjcool/keycloak-cas-services
    tags: true
    jdk: oraclejdk8